### ISSUE TITLE
Cant find stash_member_model_pi.php

### ISSUE THREAD

**Issue by klibansky** [croxton/Mustash#15]
I'm getting this error after upgrading EE5 to EE6 and Mustash to latest (php7.4).

Warning
require_once(user/addons/mustash/plugins/stash_member_model_pi.php): failed to open stream: No such file or directory
user/addons/mustash/libraries/Mustash_lib.php, line 93
Severity: E_WARNING

**Comment by croxton** [comment]
I think I removed that plugin because the member / role functionality in EE6 is revised and the logic of cache clearing based on role no longer made sense. You should be able to go to the Mustash plugin settings and save the settings to remove it, assuming you had checked the checkbox for it in a previous version of Mustash.
